-- 001_create_legal_domains.sql
-- Legal situation categories (open set: new domains can be added later).
-- UUIDs are generated by the application (uuid.uuid4()).

CREATE TABLE IF NOT EXISTS legal_domains (
    id          UUID PRIMARY KEY,
    key         VARCHAR(64) UNIQUE NOT NULL,
    name        VARCHAR(255) NOT NULL,
    description TEXT,
    is_active   BOOLEAN NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE legal_domains IS
    'Legal situation categories for Sahayak. New domains can be added at any time.';
COMMENT ON COLUMN legal_domains.key IS
    'Stable machine key used by CSV importers and retrieval (e.g. consumer, family).';