"Schema models for conversation API contracts."

from pydantic import BaseModel, Field
from typing import Optional


class Citation(BaseModel):
    """A citation grounding the AI's answer to a retrieved legal provision.

    Every field is copied from the database row that retrieval returned. The
    model never contributes citation content: an answer can only cite records
    that were actually retrieved.
    """

    document: str = Field(..., description="Title of the legal document")
    section: str = Field(..., description="Section number or article title")
    provision: str = Field(..., description="Provision text or heading")
    source: str = Field(..., description="Source name")
    source_url: Optional[str] = Field(None, description="Official URL if available")
    score: float = Field(..., description="Relevance score 0.0-1.0")

    # --- source traceability (Phase 10) --------------------------------
    source_id: Optional[str] = Field(None, description="sources.id")
    source_type: Optional[str] = Field(
        None, description="Source type (e.g. law_commission, court, government)"
    )
    source_is_verified: bool = Field(
        False, description="Database verification state of the cited source"
    )

    # --- traceability (Phase 5) ----------------------------------------
    document_id: Optional[str] = Field(None, description="legal_documents.id")
    provision_id: Optional[str] = Field(
        None, description="legal_provisions.id backing this chunk"
    )
    chunk_id: Optional[str] = Field(None, description="knowledge_chunks.id")
    chunk_index: Optional[int] = Field(None, description="Chunk position")
    section_title: Optional[str] = Field(None, description="Provision heading")
    domain: Optional[str] = Field(None, description="Legal domain key")
    is_verified: bool = Field(
        False, description="Database verification state of the cited chunk"
    )

    # --- currentness (Phase 10) ---------------------------------------
    currentness_status: str = Field(
        "unknown",
        description=(
            "Currentness status of the legal provision: "
            "current|amended|repealed|historical|unknown. "
            "Preserved from database metadata; never invented."
        ),
    )


class FollowUpQuestion(BaseModel):
    """A suggested follow-up question for the user."""
    question: str = Field(..., description="The follow-up question text")
    reason: Optional[str] = Field(None, description="Why this follow-up is suggested")


class ConversationResponse(BaseModel):
    """Structured AI response grounded on retrieved legal provisions."""

    answer: str = Field(..., description="The AI's answer in the user's language")
    citations: list[Citation] = Field(
        default_factory=list,
        description="Legal provisions cited as the basis for the answer",
    )
    follow_up_questions: list[FollowUpQuestion] = Field(
        default_factory=list,
        description="Suggested follow-up questions",
    )
    needs_clarification: bool = Field(
        default=False,
        description="Whether the response identifies missing information",
    )
    confidence: str = Field(
        ..., description="Confidence level: high|medium|low",
    )
    disclaimer: str = Field(
        ...,
        description="Disclaimer about legal advice",
    )

    # --- outcome labelling (Phase 5) -----------------------------------
    # ``status`` keeps the outcomes distinguishable instead of collapsing them
    # into one empty answer:
    #   answered            - grounded answer generated by the LLM
    #   no_verified_context - matches exist, but none are verified
    #   no_match            - nothing matched the question at all
    #   llm_unavailable     - verified context found, generation failed
    #   retrieval_error     - the legal knowledge base could not be queried
    status: str = Field(
        "answered",
        description=(
            "answered|no_verified_context|no_match|llm_unavailable|retrieval_error"
        ),
    )
    grounded: bool = Field(
        False, description="True only when the answer came from verified context"
    )
    generation: str = Field(
        "none", description="llm|unavailable|none"
    )
    llm_provider: Optional[str] = Field(None, description="Provider that generated it")
    llm_model: Optional[str] = Field(None, description="Model that generated it")
    llm_error: Optional[str] = Field(
        None,
        description=(
            "Client-safe failure kind: not_configured|timeout|provider_error|"
            "malformed_response"
        ),
    )
    retrieval_status: Optional[str] = Field(
        None, description="ok|no_match|unverified_only|error"
    )
    retrieval_total_found: int = Field(
        0, description="Verified matches found for the question"
    )
    unverified_match_count: int = Field(
        0, description="Matches that exist but are not verified"
    )
    search_terms: list[str] = Field(
        default_factory=list,
        description="Query terms used for retrieval (explainability)",
    )
    audio: Optional[str] = Field(
        None, description="Base64 encoded audio from TTS (if voice input)"
    )


class ClarificationRequest(BaseModel):
    """A request for clarification from the user."""

    question: str = Field(..., description="The clarification question")
    missing_info: str = Field(
        ..., description="What information is missing",
    )
    suggested_approach: str = Field(
        ..., description="How to proceed with the information",
    )


class ConversationMessage(BaseModel):
    """One stored turn, exposed without internal identifiers."""

    role: str = Field(..., description="user|assistant|system")
    content: str = Field("", description="Message text")
    created_at: Optional[str] = Field(None, description="Creation timestamp")


class ConversationStatus(BaseModel):
    """Current conversation session status."""

    session_id: str = Field(..., description="Unique session identifier")
    status: str = Field(..., description="Session status (active, ended)")
    language: str = Field("nepali", description="User's preferred language")
    message_count: int = Field(
        default=0,
        description="Number of messages in the conversation",
    )
    started_at: Optional[str] = Field(
        None, description="When the conversation started",
    )
    messages: list[ConversationMessage] = Field(
        default_factory=list,
        description="Recent turns, oldest first (capped server-side)",
    )